-- Weekly Thursday (Pro) + Weekly Sunday (Student) tournaments for the rest of 2026, starting 19 Mar 2026 (NZ time).
-- Safe to re-run: skips rows that already exist for the same local date + event_type.

ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS event_type VARCHAR(50);
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS participant_category VARCHAR(50);
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS min_players INTEGER;

INSERT INTO public.tournaments (
  name,
  description,
  tournament_type,
  start_date,
  entry_fee,
  min_players,
  max_players,
  status,
  event_type,
  participant_category
)
SELECT *
FROM (
SELECT 'Weekly Tournament — 19 Mar 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-03-19 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 26 Mar 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-03-26 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 02 Apr 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-04-02 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 09 Apr 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-04-09 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 16 Apr 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-04-16 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 23 Apr 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-04-23 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 30 Apr 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-04-30 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 07 May 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-05-07 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 14 May 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-05-14 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 21 May 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-05-21 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 28 May 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-05-28 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 04 Jun 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-06-04 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 11 Jun 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-06-11 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 18 Jun 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-06-18 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 25 Jun 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-06-25 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 02 Jul 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-07-02 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 09 Jul 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-07-09 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 16 Jul 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-07-16 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 23 Jul 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-07-23 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 30 Jul 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-07-30 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 06 Aug 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-08-06 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 13 Aug 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-08-13 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 20 Aug 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-08-20 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 27 Aug 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-08-27 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 03 Sep 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-09-03 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 10 Sep 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-09-10 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 17 Sep 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-09-17 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 24 Sep 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-09-24 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 01 Oct 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-10-01 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 08 Oct 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-10-08 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 15 Oct 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-10-15 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 22 Oct 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-10-22 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 29 Oct 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-10-29 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 05 Nov 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-11-05 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 12 Nov 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-11-12 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 19 Nov 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-11-19 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 26 Nov 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-11-26 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 03 Dec 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-12-03 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 10 Dec 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-12-10 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 17 Dec 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-12-17 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 24 Dec 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-12-24 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Weekly Tournament — 31 Dec 2026'::text,
       'Weekly Thursday tournament at Joy Billiards Hamilton (Pro / Adult).'::text,
       'single_elimination'::varchar,
       ('2026-12-31 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_pro'::varchar,
       'adult'::varchar
UNION ALL
SELECT 'Student Tournament — 22 Mar 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-03-22 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 29 Mar 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-03-29 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 05 Apr 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-04-05 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 12 Apr 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-04-12 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 19 Apr 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-04-19 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 26 Apr 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-04-26 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 03 May 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-05-03 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 10 May 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-05-10 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 17 May 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-05-17 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 24 May 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-05-24 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 31 May 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-05-31 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 07 Jun 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-06-07 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 14 Jun 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-06-14 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 21 Jun 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-06-21 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 28 Jun 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-06-28 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 05 Jul 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-07-05 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 12 Jul 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-07-12 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 19 Jul 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-07-19 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 26 Jul 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-07-26 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 02 Aug 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-08-02 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 09 Aug 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-08-09 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 16 Aug 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-08-16 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 23 Aug 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-08-23 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 30 Aug 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-08-30 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 06 Sep 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-09-06 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 13 Sep 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-09-13 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 20 Sep 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-09-20 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 27 Sep 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-09-27 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 04 Oct 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-10-04 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 11 Oct 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-10-11 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 18 Oct 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-10-18 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 25 Oct 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-10-25 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 01 Nov 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-11-01 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 08 Nov 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-11-08 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 15 Nov 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-11-15 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 22 Nov 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-11-22 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 29 Nov 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-11-29 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 06 Dec 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-12-06 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 13 Dec 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-12-13 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 20 Dec 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-12-20 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
UNION ALL
SELECT 'Student Tournament — 27 Dec 2026'::text,
       'Weekly Sunday student tournament at Joy Billiards Hamilton.'::text,
       'single_elimination'::varchar,
       ('2026-12-27 19:00:00'::timestamp AT TIME ZONE 'Pacific/Auckland'),
       20::numeric,
       8::integer,
       NULL::integer,
       'registration'::varchar,
       'weekly_student'::varchar,
       'student'::varchar
) AS v(name, description, tournament_type, start_date, entry_fee, min_players, max_players, status, event_type, participant_category)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tournaments t
  WHERE t.event_type IS NOT DISTINCT FROM v.event_type
    AND (t.start_date AT TIME ZONE 'Pacific/Auckland')::date
        = (v.start_date AT TIME ZONE 'Pacific/Auckland')::date
);

